### ISSUE TITLE
User Tesing Assignment

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#100]
https://piazza.com/class/ikd0zgznxw63jx?cid=332

Now that your development is nearly finished and delivery and deployment is approaching, it is time to test your prototype with users and get their feedback. 
 
1. Go over your user test documents and prepare them for user tests with your system.
2. Pick scenarios such as adding content to existing topics, searching existing and non-existing content etc.
3. Conduct user tests with at least 3 different users. Have them fill your user test forms. 
4. Scan and submit the user tests to GitHub before the lecture on December 15th.

**Comment by slmtpz** [comment]
Don't forget to change "Test Plan" according to our current system. (steps)
3 and 8 are the most important ones, (they are enough in my opinion)

**Comment by gokberkerust** [comment]
Done and wiki page updated.
