### ISSUE TITLE
Videos will be watched

### ISSUE THREAD

**Issue by ddemirci** [bounswe/bounswe2016group4#11]
Hi, everyone.
The given links below are our homework.Due date is 23th Feb

https://www.youtube.com/watch?v=XU0llRltyFM
https://www.youtube.com/watch?v=6sqvWEI1CVg&spfreload=10

These are optional:
 https://www.youtube.com/watch?v=kce2L23yLcw
 https://www.youtube.com/watch?v=rrkrvAUbU9Y

See you soon

**Comment by alpteko** [comment]
where should we put the links we found ? First we put here than select good ones?
