### ISSUE TITLE
Documentation about 'Scrum'

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#12]
- Watch the video at https://www.youtube.com/watch?v=XU0llRltyFM
- Document your observations and relevant comments about Scrum on wiki.

**Comment by alpteko** [comment]
I created a documentation space to  put them in or should we put in project documentation

**Comment by slmtpz** [comment]
What you did was actually what should be done. We need Project Documentation tab for our own course project. Therefore move your works in Project Documentation to Documentation tab so that they would not be mixed to each other.

**Comment by slmtpz** [comment]
Also, I highly recommend you guys that you should add some pictures about Scrum and Five Dysfunctions to their corresponding pages so that what you want to tell will be clear and more readable. You can see how to do that in the code of [that](https://github.com/bounswe/bounswe2016group4/wiki/Seleme-Topuz) page.

**Comment by alpteko** [comment]
www.azquotes.com, this site is very useful if you want to create some picture with quotes

**Comment by slmtpz** [comment]
Remember adding a References part like I did in [More](https://github.com/bounswe/bounswe2016group4/wiki/More-Software-Development-Related-Material) if you use some references !!!

**Comment by muhammednursoy** [comment]
I am finished with [the scrum video documantation](https://github.com/bounswe/bounswe2016group4/wiki/Scrum:-An-Agile-Methodology-Practice) .

**Comment by slmtpz** [comment]
Cool, it seems nice, you can close the issue as soon as you are done :)

**Comment by alpteko** [comment]
really nice work

**Comment by muhammednursoy** [comment]
thanks, if there is no more suggestions or corrections i am closing this issue.
