### ISSUE TITLE
Documentation about 'Five Dysfunctions Of a Team'

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#13]
- Watch the video at https://www.youtube.com/watch?v=6sqvWEI1CVg&spfreload=10
- Document your observations and relevant comments about 'Five Dysfunctions Of a Team' on wiki.

**Comment by alpteko** [comment]
Ok. I will handle it :)

**Comment by alpteko** [comment]
I finished the work, if you have any ideas or any corrections, fell free to come up with a issue :)

**Comment by slmtpz** [comment]
Remember adding a References part like I did in [More](https://github.com/bounswe/bounswe2016group4/wiki/More-Software-Development-Related-Material) if you use some references !!!
