### ISSUE TITLE
Discussion on customization of labels for issues, specifically for 'priority' labels.

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#19]
Hey pals, I wonder if you have the same condition for feeling a little awkward when you want to use priority labels. Initially, there was no 'priority' labels in the default labels of GitHub. When I added them, I added them as 3 groups: '**priority-high**', '**priority-middle**', **'priority-low**'.
Well, I think that issues that we will create, mostly will be on the same priority, surely some of them will be most urgent ones and accordingly most prioritized. But I think we will have no need of such 3 labels, 1 would be enough I guess, only red one, '**priority**'.
In the old, it was kinda we need to prioritize every issues, which we did not do this on homework 2 and some other issues :). New model suggests using of 'priority' tag, will be only on the most urgent ones.
What do you think ? Should we change labels, or do you want to add/change some more ? My vote will be on the new model that I just suggested.
@claudiusalp @ddemirci @caksoy26 @kutaycandan @gokberkerust @muhammednursoy @guneydd

**Comment by alpteko** [comment]
I think we should talk it in the first meeting , beacuse it is very important for team. we must determine some conventions about our homeworks and tasks. For example, if somebody thinks smthng is very very important, everybody consider it in this way. Eventually, two option for priority is ok.

**Comment by ghost** [comment]
I agree with you guys, we should decide our priority criteria in the first meeting.
