### ISSUE TITLE
User Requirements

### ISSUE THREAD

**Issue by kutaycandan** [bounswe/bounswe2016group4#23]
User Requirements must be done.

**Comment by alpteko** [comment]
I am with you

**Comment by alpteko** [comment]
I completed some parts of the task , please check them up some in case some mistakes ambiguity  @ddemirci  @kutaycandan we must be consistent

**Comment by slmtpz** [comment]
There are some bad english, enumeration and uses of 'shall'. I advise you to look over the text again.
'to registered' should be 'to register'.
indenting of '1.2' is wrong.
and please don't use 'shall' if the user does not have to do something. For example, guest users not 'shall' register to the system but may/can register. I'm not sure if these are the exact uses but, its not essential for guest users to register to the system to use it as we spoke earlier.
@claudiusalp

**Comment by slmtpz** [comment]
Oh my bad about uses of shall, you said 'shall be able to'. It's correct, still we need to be careful

**Comment by alpteko** [comment]
You have a point. Shall has a different meanings , I used shall be able to if there is a important choice such as shall able to change visibility but creating profile or search is goal of our project so I preferred shall alone. In brief , we must discuss it in whatsapp :)
