### ISSUE TITLE
Requirement changes

### ISSUE THREAD

**Issue by akifcorduk** [bounswe/bounswe2016group4#49]
Requirement 1.2.1.2 and 1.2.2.5 should be changed. 1.2.1.2 : There is no need for e-mail confirmation. It is enough to just send an information e-mail about that user has changed the password. 1.2.2.5: It says "shall be able to disable" it is ambigious.

**Comment by alper111** [comment]
1.2.1.2.1 is removed.
1.2.2.5 is now as follows: "Registered users shall be able to use advanced search with a different eating preference."
