### ISSUE TITLE
Forgot my password page

### ISSUE THREAD

**Issue by akifcorduk** [bounswe/bounswe2016group4#50]
There is no "forgot password?" option in the requirements but in mock-up there is! There should be an option for forgetting password and user should reset the password with e-mail address. It should be implemented via sending a system generated password to the user via e-mail.

**Comment by slmtpz** [comment]
As our teacher commented last lesson, there may/should not be specific requirements like that. Our requirements actually can only cover the general concept of the project. Better not bother add it. Nice catch tho. Probably we need such a feature but we can think about it later, after we finish implementing our requirements.
