### ISSUE TITLE
Mockups are needed to be redesigned.

### ISSUE THREAD

**Issue by alper111** [bounswe/bounswe2016group4#51]
- [x]  Mockup 3 - Add food nutritions, which eating preferences it is suitable,  suggestions about the food.
- [x]  Mockup 4.b - Add all advanced search features such as ingredients, nutritions etc.  
- [x]  Mockup 5 - Add nutritions, which eating preference it is suitable.
- [ ]  Mockup 7.a - There is no "list" feature in registered user page. Also there is no mockup for lists.

**Comment by alper111** [comment]
I am doing first two elements on the list.

**Comment by alper111** [comment]
Actually there is "list" feature in the mockup 6, I didn't see. Still there is no mockup for lists.

**Comment by ddemirci** [comment]
Mockup 5 has been updated
