### ISSUE TITLE
Android Task Selection

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#52]
As we discussed in [the meeting](https://github.com/bounswe/bounswe2016group4/wiki/Meeting-%2313) Android development members should decide their task schedule between our next 2 milestones and write the tasks down on discord. Also, after writing them, you should compare with the Web development members.

**Comment by akifcorduk** [comment]
We discussed our task schedule and posted it on discord.

**Comment by slmtpz** [comment]
We must wait for the next meeting in Tuesday, for all groups to verify the tasks in order to make sure that they will not change any time sooner.
