### ISSUE TITLE
Tagging Foods

### ISSUE THREAD

**Issue by slmtpz** [bounswe/bounswe2016group4#63]
How do I know a food's ID just after it is inserted. I was told I should add tags after I insert the food. However I don't know foods id to insert tags using db_insert_tag which requires food id. 
```
    if nutrition_dict is not None:
        if db_insert_food(food_dict, nutrition_dict):
            return True
```
Either db_insert_function should return foods id after it is inserted or inserting tag process should be done in db_insert_food which would be wrong since a food could be tagged later. So I need foods id return in its insert function.

**Comment by alpteko** [comment]
def db_insert_food(food_dict, nutrition_dict) will return food_id
